### ISSUE TITLE
Plugin Possibility?

### ISSUE THREAD

**Issue by ahainen** [alyssaxuu/figma-to-google-slides#1]
Ahoy - I love this and I had forgotten to come back until now. I recall not being able to get it setup the first time I tried it - wasn't able to, but I meant to come back to it. That said, I recently saw Figma plugins launch - any possibility of this being on there?

**Comment by alyssaxuu** [comment]
Hey Ahainen, that's a good idea (and could easily have more extra features & settings for the exports), but I don't think I'll be personally pursuing that further myself as I'm rather busy nowadays, and I would have to rewrite the entire code to work within the Figma plugin infrastructure. I'd be more than glad if anyone wanted to give it a shot though :)
