### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by ccolegate** [alyssaxuu/figma-to-google-slides#3]
The Chrome Extension doesn't seem to be working for me, no extra button being inserted in the toolbar. 

In the console there is the following error?

Uncaught TypeError: Cannot read property 'insertAdjacentHTML' of undefined
    at run (popup.js:48)
    at isLoaded (popup.js:38)

**Comment by alyssaxuu** [comment]
That was due to Figma applying some changes that modified the names of the elements I was appending to. Should be fixed now (update to version 10.5).
